CREATE TABLE IF NOT EXISTS requests (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name       VARCHAR(100) NOT NULL DEFAULT '',
  phone      VARCHAR(30)  NOT NULL DEFAULT '',
  email      VARCHAR(150) NOT NULL DEFAULT '',
  message    TEXT         NOT NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
